name: gis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - ipykernel

  # ciencia de datos / GIS
  - numpy
  - pandas
  - matplotlib
  - geopandas
  - rasterio
  - shapely
  - pyproj
  - fiona
  - gdal
  - libgdal-jp2openjpeg

  # visualización / web
  - folium
  - plotly
  - nodejs>=18

  # backend + DB
  - flask
  - flask-login
  - flask-sqlalchemy
  - flask-mail
  - sqlalchemy
  - psycopg2
  - geoalchemy2

  # imágenes y STAC / Planetary Computer
  - pillow
  - pystac-client
  - planetary-computer

  - pip:
      - dash
      - python-dotenv